// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBWD2FGAR-qsXHeOQDVa0lAhCw0_vT-Y8',
    appId: '1:209024763157:web:a1470707b923656d1cd51c',
    messagingSenderId: '209024763157',
    projectId: 'entitle-guard-4c857',
    authDomain: 'entitle-guard-4c857.firebaseapp.com',
    storageBucket: 'entitle-guard-4c857.appspot.com',
    measurementId: 'G-MZ5ZKVBLJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXsIePV_v9PfbHHW3-6ArzTJL2bKmfWs8',
    appId: '1:209024763157:android:34edfe9812258eeb1cd51c',
    messagingSenderId: '209024763157',
    projectId: 'entitle-guard-4c857',
    storageBucket: 'entitle-guard-4c857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNZUfkSDhAolSrnfsdwhmOU6Im9FNP8g',
    appId: '1:209024763157:ios:debd5ea0b03e4dc61cd51c',
    messagingSenderId: '209024763157',
    projectId: 'entitle-guard-4c857',
    storageBucket: 'entitle-guard-4c857.appspot.com',
    iosBundleId: 'com.example.entitleGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfNZUfkSDhAolSrnfsdwhmOU6Im9FNP8g',
    appId: '1:209024763157:ios:082bf7ffc162b9011cd51c',
    messagingSenderId: '209024763157',
    projectId: 'entitle-guard-4c857',
    storageBucket: 'entitle-guard-4c857.appspot.com',
    iosBundleId: 'com.example.entitleGuard.RunnerTests',
  );
}
